webtalk_init -webtalk_dir D:/Facultate/SSC/Proiect/inmultitor/inmultitor.sim/sim_1/behav/xsim/xsim.dir/TB_inmultire_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan  8 15:31:59 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7dda9397-5379-4449-be4a-473c386bdb84" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e167ac3c816942fab21ee60bd347844c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "254" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "22" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "212 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "74 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1944" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "590" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "3.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "101960_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1721933497 -regid "" -xml D:/Facultate/SSC/Proiect/inmultitor/inmultitor.sim/sim_1/behav/xsim/xsim.dir/TB_inmultire_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Facultate/SSC/Proiect/inmultitor/inmultitor.sim/sim_1/behav/xsim/xsim.dir/TB_inmultire_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Facultate/SSC/Proiect/inmultitor/inmultitor.sim/sim_1/behav/xsim/xsim.dir/TB_inmultire_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
